###
POST http://localhost:3000/email-otp
Content-Type: application/json

{
    "email":"zouqe42@gmail.com"
}
###
POST http://localhost:3000/create-playlist
Content-Type: application/json

{
    "name":"Some New Playlist",
    "description": "Some Description for the playlist",
    "videos":[
        {
            "title":"Title 1",
            "path": "video-uploads\\1652079008111.mp4",
            "duration": "0:4"
        },
        {
            "title":"Title 2",
            "path": "video-uploads\\1652079008111.mp4",
            "duration": "0:4"
        },
        {
            "title":"Title 3",
            "path": "video-uploads\\1652079008111.mp4",
            "duration": "0:4"
        }
    ],
    "images":[
        "image-uploads\\1652079089867.png",
        "image-uploads\\1652079089867.png",
        "image-uploads\\1652079089867.png"
    ],
    "topic":"6278ba41fd0c3e1a5996902b"
}
###
POST http://localhost:3000/create-topic
Content-Type: application/json

{
    "name":"Some New Topic",
    "description": "Some Description for the topic",
    "images":[
        "image-uploads\\1652079089867.png",
        "image-uploads\\1652079089867.png",
        "image-uploads\\1652079089867.png"
    ],
    "price":"50"
}

###
GET http://localhost:3000/get-all-topics 

###
GET http://localhost:3000/get-topic?_id=6278ba41fd0c3e1a5996902b
###
GET http://localhost:3000/get-topic-playlists?_id=6278ba41fd0c3e1a5996902b
###
PUT http://localhost:3000/update-topic
Content-Type: application/json

{
    "_id":"625e55db14ba331cd79ef7a4",
    "name":"Personal Topic",
    "description": "Some Description for the topic",
    "images":[
        "image-uploads\\1650349172242.png",
        "image-uploads\\1650349172242.png",
        "image-uploads\\1650349172242.png"
    ],
    "price":"450"
}
###
DELETE http://localhost:3000/delete-topic
Content-Type: application/json

{
    "_id":"625e55db14ba331cd79ef7a4"
}
###
DELETE http://localhost:3000/delete-playlist
Content-Type: application/json

{
    "_id":"625e57073b0aaabe618629bb"
}
###
GET http://localhost:3000/get-all-playlists 
###
GET http://localhost:3000/get-playlist?_id=6278ba86f6c99b2d51d9a568
###
PUT http://localhost:3000/add-image-in-playlist
Content-Type: application/json

{
    "_id":"6278ba86f6c99b2d51d9a568",
    "image":"image-uploads\\1652079089867.png"
}
###
PUT http://localhost:3000/add-video-in-playlist
Content-Type: application/json

{
    "_id":"6278ba86f6c99b2d51d9a568",
    "video": {
        "path": "video-uploads\\1652079008111.mp4",
        "duration": "0:4"
    }
}
###
DELETE http://localhost:3000/remove-image-from-playlist
Content-Type: application/json

{
    "_id":"625e5741a8af67231727ce49",
    "image":"image-uploads\\1650349172242.png"
}
###
DELETE http://localhost:3000/remove-video-from-playlist
Content-Type: application/json

{
    "_id":"625e5741a8af67231727ce49",
    "video":"video-uploads\\1650349203820.mp4"
}
###
POST http://localhost:3000/create-admin
Content-Type: application/json

{
    "image":"image-uploads\\1650349172242.png",
    "fullName":"name of admin",
    "dob":"2022-04-19T06:38:16.403Z",
    "jobTitle":"Job",
    "email":"asd@asd.asd",
    "password":"asd"
}
###
DELETE http://localhost:3000/delete-admin
Content-Type: application/json

{
    "email":"asd@asd.asd"
}
###
GET http://localhost:3000/get-admin?email=asd@asd.asd
###
PUT http://localhost:3000/login-admin
Content-Type: application/json

{
    "email":"asd@asd.asd",
    "password":"asd"
}
###
PUT http://localhost:3000/logout-admin
Content-Type: application/json

{
    "email":"asd@asd.asd"
}
###
PUT http://localhost:3000/update-admin-password
Content-Type: application/json

{
    "email":"asd@asd.asd",
    "password":"123"
}
###
PUT http://localhost:3000/update-admin-profile
Content-Type: application/json

{
    "email":"asd@asd.asd",
    "image":"asd",
    "fullName":"asd",
    "dob":"2022-04-19T06:38:16.403Z",
    "jobTitle":"asd"
}
###
POST http://localhost:3000/create-user
Content-Type: application/json

{
    "fullName":"asd",
    "email":"asd@asd.asd",
    "password":"asd"
}
###
DELETE http://localhost:3000/delete-user
Content-Type: application/json

{
    "email":"asd@asd.asd"
}
###
GET http://localhost:3000/get-user?email=asd@asd.asd
###
PUT http://localhost:3000/login-user
Content-Type: application/json

{
    "email":"asd@asd.asd",
    "password":"asd"
}
###
PUT http://localhost:3000/logout-user
Content-Type: application/json

{
    "email":"asd@asd.asd"
}
###
PUT http://localhost:3000/update-user-password
Content-Type: application/json

{
    "email":"asd@asd.asd",
    "password":"123"
}
###
PUT http://localhost:3000/update-user-profile
Content-Type: application/json

{
    "email":"zouqe42@gmail.com",
    "fullName":"asdasda",
    "dob":"2022-05-09T06:11:53.295Z",
    "address":"dhok khabba"
}

###
PUT http://localhost:3000/add-card
Content-Type: application/json

{
    "email":"asd@asd.asd",
    "cardNumber":"123",
    "expiryMonth":"12",
    "expiryYear":"12",
    "securityCode":"123",
    "firstName":"asd",
    "lastName":"asd"
}
###
POST http://localhost:3000/create-subscription
Content-Type: application/json

{
    "_id":"6278ba1c9992fe8a40b3ff4e",
    "topic":"6278ba41fd0c3e1a5996902b",
    "playlist":"6278ba41fd0c3e1a5996902b",
    "subscriptionTenure":{
        "tenureType":"Daily",
        "startDate":"2022-04-19T06:38:16.403Z",
        "endDate":"2022-04-19T06:38:16.403Z"
    },
    # "totalPrice":"432",
    "cardDetails":{
        "cardNumber":"4242424242424242",
        "expiryMonth":"04",
        "expiryYear":"24",
        "cvc":"123"
    }
}

###
DELETE  http://localhost:3000/delete-subscription
Content-Type: application/json

{
    "_id":"625e5bc8ac59f2acc0af5186",
    "user_id":"625e5a541db9364fc3e8bbc7"
}
###
GET http://localhost:3000/get-all-subscriptions
###
GET http://localhost:3000/get-user-subscriptions?_id=627a09b03a9ae7827aee8755
###
PUT http://localhost:3000/update-subscription
Content-Type: application/json

{
    "_id":"625e5c666144e8bef8e6adf7",
    "topic":"625e56e03b0aaabe618629b9",
    "subscriptionTenure":{
        "tenureType":"Daily",
        "startDate":"2022-04-19T06:38:16.403Z",
        "endDate":"2022-04-19T06:38:16.403Z"
    },
    "totalPrice":"1234"
}